export interface InstalledSkillItem {
  id: string;
  description: string;
}

export interface InstalledSkillCategory {
  id: string;
  title: string;
  summary: string;
  skills: InstalledSkillItem[];
}

export const INSTALLED_SKILLS_CATALOG: InstalledSkillCategory[] = [
  {
    id: 'legal',
    title: '法务',
    summary: '适用于合同审查、法律分析、合规审查、法律文书与法务策略场景。',
    skills: [
      { id: 'china-contract-review', description: '中国合同审查，适合 NDA、MSA、采购、劳动等合同风险识别。' },
      { id: 'china-legal-analysis', description: '中国法律问题分析，适合法律适用与条文解读。' },
      { id: 'china-legal-query', description: '中国法律法规查询与检索。' },
      { id: 'compliance-review', description: '合规审查，适合制度、流程与材料合规性检查。' },
      { id: 'contract-generator', description: '根据业务需求生成合同初稿。' },
      { id: 'contract-review-agent', description: '对合同条款进行结构化审查并给出修改建议。' },
      { id: 'lawyer', description: '通用法律顾问类技能。' },
      { id: 'legal-advisor', description: '法律咨询与法务策略辅助。' },
      { id: 'legal-compliance-hub', description: '法务合规一体化技能中心，覆盖合同、审计、监管框架、风险评分。' },
      { id: 'legal-document-assistant', description: '法律文书辅助撰写与整理。' },
      { id: 'standards-compliance-checker', description: '按标准/规范检查内容是否合规。' },
    ],
  },
  {
    id: 'finance',
    title: '财税审计',
    summary: '适用于税务、财务分析、会计、费用报销、发票处理、审计与财税辅助场景。',
    skills: [
      { id: 'ai-invoice-generator', description: '自动生成发票或发票类文档。' },
      { id: 'china-tax-law', description: '中国税法查询与税务规则参考。' },
      { id: 'data-analyst-pro', description: '通用数据分析，也可辅助审计与异常发现。' },
      { id: 'expense-agent', description: '费用报销与费用类材料处理辅助。' },
      { id: 'expense-invoice-ocr', description: '发票 OCR 识别，适合票据数字化。' },
      { id: 'finance-accounting', description: '财务会计处理与核算辅助。' },
      { id: 'finance-analysis', description: '财务指标分析、经营分析辅助。' },
      { id: 'finance-report-analyzer', description: '财务报告阅读、分析与提炼。' },
      { id: 'invoice-template', description: '发票模板生成与整理。' },
      { id: 'openclaw-accounting', description: '通用会计辅助工具。' },
      { id: 'tax-calculator-cn', description: '中国税务计算器。' },
      { id: 'tax-professional', description: '税务专业辅助，适合税务咨询与方案判断。' },
    ],
  },
  {
    id: 'engineering',
    title: '研发',
    summary: '适用于编码开发、代码生成、测试、Git 工作流、研发知识库与工程协作场景。',
    skills: [
      { id: 'agentic-coding', description: '面向复杂开发任务的 Agent 式编码工作流。' },
      { id: 'ai-agent-evaluator', description: '评估 AI Agent/流程效果与表现。' },
      { id: 'coding-lead', description: '偏研发负责人的编码执行与推进辅助。' },
      { id: 'git-cli', description: 'Git 命令行辅助。' },
      { id: 'git-essentials', description: 'Git 基础能力与常用操作。' },
      { id: 'git-helper', description: 'Git 使用助手与问题排查。' },
      { id: 'git-workflows', description: 'Git 分支、协作、工作流实践辅助。' },
      { id: 'rag-construction', description: 'RAG 知识库/检索增强系统构建辅助。' },
      { id: 'self-improving-agent', description: '自我迭代、自我改进型 Agent 思路辅助。' },
      { id: 'test-generator', description: '自动生成测试用例。' },
      { id: 'test-runner', description: '测试执行与测试流程辅助。' },
      { id: 'vibe-coding', description: '更轻量、强调快速产出的编码辅助。' },
    ],
  },
  {
    id: 'operations-admin',
    title: '行政',
    summary: '适用于日程、任务、文档流转、HR、提醒、日常办公行政支持等场景。',
    skills: [
      { id: 'calendar-manager', description: '日历管理、日程安排与查看。' },
      { id: 'coordinate-meeting', description: '会议协调、约会时间统筹。' },
      { id: 'daily-report-writer', description: '自动整理和生成日报。' },
      { id: 'email-daily-summary', description: '汇总邮件并生成每日摘要。' },
      { id: 'file-auto-organizer', description: '自动整理和归类文件。' },
      { id: 'hr-assistant', description: 'HR 通用辅助。' },
      { id: 'hr-policy-generator', description: '生成人事制度、HR 政策草稿。' },
      { id: 'lark-calendar', description: '飞书日历相关操作辅助。' },
      { id: 'meeting-prep', description: '会议前资料准备与清单整理。' },
      { id: 'meeting-to-action', description: '会议纪要转行动项。' },
      { id: 'note-taker', description: '笔记记录与整理。' },
      { id: 'office-document-specialist-suite', description: '综合 Office 文档处理套件。' },
      { id: 'office-secretary', description: '偏秘书型办公辅助。' },
      { id: 'openclaw-reminder', description: '提醒事项、待办提醒。' },
      { id: 'schedule-feishu', description: '飞书日程安排与日历操作。' },
      { id: 'smart-meeting-minutes-cn', description: '中文会议纪要智能整理。' },
      { id: 'sme-hr-automation', description: '中小团队 HR 自动化。' },
      { id: 'task-planner', description: '任务拆解与规划。' },
      { id: 'task-tracker-pro', description: '任务跟踪与进度管理。' },
      { id: 'weekly-report-writer', description: '自动整理和生成周报。' },
    ],
  },
  {
    id: 'operations-growth',
    title: '运营',
    summary: '适用于内容运营、平台运营、市场运营、流量运营和业务增长场景。',
    skills: [
      { id: 'douyin-operations', description: '抖音平台运营辅助。' },
      { id: 'internet-marketing', description: '网络推广与线上运营辅助。' },
      { id: 'market-analysis-cn', description: '中文市场分析与竞品分析辅助。' },
      { id: 'search-x', description: '搜索增强或检索类专项工具。' },
    ],
  },
  {
    id: 'sales',
    title: '销售',
    summary: '适用于销售线索跟踪、销售对话、销售方法与销售流程管理场景。',
    skills: [
      { id: 'sales-dialogue', description: '销售对话与话术辅助。' },
      { id: 'sales-mastery', description: '销售方法论与成交辅助。' },
      { id: 'sales-pipeline-tracker', description: '销售机会/客户管道跟踪。' },
    ],
  },
  {
    id: 'marketing',
    title: '营销',
    summary: '适用于营销策略、营销分析、营销文案、传播和推广场景。',
    skills: [
      { id: 'marketing-analytics', description: '营销数据分析。' },
      { id: 'marketing-copywriter', description: '偏营销文案创作。' },
      { id: 'marketing-copywriting', description: '营销内容与文案撰写。' },
      { id: 'marketing-strategy-pmm', description: '偏 PMM 视角的营销策略能力。' },
    ],
  },
  {
    id: 'utilities',
    title: '常用工具',
    summary: '适用于文档、表格、PPT、PDF、转换、翻译、搜索、天气等高频办公通用场景。',
    skills: [
      { id: 'brave-web-search', description: 'Brave 搜索能力。' },
      { id: 'convert-units', description: '单位换算工具。' },
      { id: 'ddg-web-search', description: 'DuckDuckGo 搜索能力。' },
      { id: 'desearch-web-search', description: 'Desearch 搜索能力。' },
      { id: 'docx', description: 'Word 文档处理。' },
      { id: 'docx-cn', description: '中文 DOCX 文档处理。' },
      { id: 'extract-tables-from-pdf', description: '从 PDF 中提取表格。' },
      { id: 'feishu-api-bitable', description: '飞书多维表格 API 工具。' },
      { id: 'feishu-doc-manager', description: '飞书文档管理。' },
      { id: 'feishu-toolkit', description: '飞书工具合集。' },
      { id: 'file-converter', description: '文件格式转换。' },
      { id: 'find-skills', description: '检索/发现 Skill。' },
      { id: 'form-builder', description: '表单生成。' },
      { id: 'glm-web-search', description: 'GLM 搜索能力。' },
      { id: 'image2text-ocr', description: '图片 OCR 识别。' },
      { id: 'local-web-search-skill', description: '本地搜索增强。' },
      { id: 'markdown-formatter', description: 'Markdown 格式化。' },
      { id: 'pdf', description: 'PDF 通用处理。' },
      { id: 'pdf-extract', description: 'PDF 内容提取。' },
      { id: 'pdf-ocr', description: 'PDF OCR 识别。' },
      { id: 'pdf-reader', description: 'PDF 阅读与提取。' },
      { id: 'pdf-smart-tool-cn', description: '中文 PDF 智能处理工具。' },
      { id: 'ppt-generator', description: 'PPT 自动生成。' },
      { id: 'ppt-maker', description: 'PPT 制作辅助。' },
      { id: 'ppt-quick-gen', description: '快速生成 PPT。' },
      { id: 'ppt-reader', description: 'PPT 阅读与提取。' },
      { id: 'pptx', description: 'PPTX 文件处理。' },
      { id: 'scnet-ocr', description: 'OCR 能力扩展。' },
      { id: 'smart-summarizer', description: '智能总结。' },
      { id: 'summarizer', description: '通用总结工具。' },
      { id: 'tavily-search', description: 'Tavily 搜索能力。' },
      { id: 'text-to-markdown', description: '文本转 Markdown。' },
      { id: 'universal-translate', description: '通用翻译。' },
      { id: 'weather', description: '天气查询。' },
      { id: 'wecom-file-detect', description: '企业微信文件识别/处理。' },
      { id: 'word-docx', description: 'Word 文档生成/处理。' },
      { id: 'xlsx', description: 'Excel 文件处理。' },
      { id: 'xlsx-cn', description: '中文 Excel 文件处理。' },
    ],
  },
  {
    id: 'other',
    title: '其他',
    summary: '适用于偏平台能力、实验性能力或专项能力的 Skill。',
    skills: [
      { id: 'lhc-stat', description: '统计类或专项数据能力。' },
      { id: 'mem0-memory', description: '记忆管理相关能力。' },
      { id: 'qinghai-solution', description: '青海方案类专项技能。' },
      { id: 'skill-vetter', description: 'Skill 安全审查与风险评估。' },
    ],
  },
];
